### PR TITLE
Hello-microverse-project | Pull Request

### PR DESCRIPTION
**Pull request by NicolasAndrehh**
# Milestone - Project Completed
In this pull request I implement the following features:

- Added a .html file that includes a `header` with the text "Hello Microverse!"
- Added a .css file that change the color of the header to `dark cyan`

### CODE REVIEW

**Review by iambenkis — COMMENTED** [review]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @NicolasAndrehh  👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project, but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark: 



 ## Required Changes ♻️

- [ ] Good job @NicolasAndrehh :+1:  setting everything up, but your PR summary should be more description as required . :100: 
Screenshot from 2023-01-10 22-44-45
You can look at this example [here](https://github.com/iambenkis/Space-X-/pull/32) and Kindly update yours!

- [ ] [**IMPORTANT NOTE**] Next time :next_track_button:  note that you are not allowed to merge your branched unless you get approved by a code reviewer, It is an important step you should always follow at microverse. :smiley: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@iambenkis** in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by NicolasAndrehh** [comment]
Hi @iambenkis, thanks for your review :D
I'll do the respective changes as soon as possible!

**Comment by NicolasAndrehh** [comment]
@iambenkis I have a question, should I request a review again?
I already do the changes on the PR summary, I think that now it's a lot better, thank you for letting me know what to improve!

**Comment by iambenkis** [comment]
Yes

**Pull request merged**
